### PR TITLE
History MySQL Integration complete

### PR DESCRIPTION
**Pull request by knilssen**
Mysql is now up and working to transfer short term saved race data to more longterm storage in a mysql database!

### CODE REVIEW

**Comment by Mattsface** [comment]
Do you know to squash commits? I should show you some time. Looked over this with a coworker she says it looks good

**Comment by Mattsface** [comment]
oops lets resolve these conflicts

**Comment by Mattsface** [comment]
I didn't take lunch so I'll take a look

**Comment by Mattsface** [comment]
why am I stumbling on this? It's just because we are missing go_websocket_server.go as far as I can tell

**Comment by knilssen** [comment]
Honestly its looking like it? I didn't spend too much time before creating the the merge to resolve the conflicts. After going back its looking more like that could be the case....

**Comment by knilssen** [comment]
Yup, it looked like for some reason it couldn't handle loosing go_websocket_server.go so I added it. Ill remove it in a commit to master once I merge the pull request.

**Pull request merged**
